; reverse the given input:

.MODEL SMALL
.STACK 100H
.CODE
MAIN PROC
;DISPLAY USER PROMPT
    MOV AH, 2
    MOV DL, '?'
    INT 21H
;INITIALIZE CHARACTER COUNT
    XOR CX,CX
;READ A CHARACTER
    MOV AH, 1
    INT 21H
;WHILE CHARACTER IS NOT A CARRIAGE RETURN DO
    WHILE_:
        CMP AL, 0DH
        JE END_WHILE
;SAVE CHARACTER ON THE STACK AND INCREMENT COUNTER
        PUSH AX
        INC CX
;READ A CHARACTER
        INT 21H
        JMP WHILE_
    END_WHILE:
;GO TO A NEW LINE
    MOV AH, 2
    MOV DL, 0DH
    INT 21H
    MOV DL,0AH
    INT 21H
    JCXZ EXIT
;FOR COUNT TIMES DO
    TOP:
;POP A CHARACTER FROM THE STACK
        POP DX
;DISPLAY IT
        INT 21H
        LOOP TOP
;END FO
EXIT:
    MOV AH, 4CH
    INT 21H
MAIN ENDP
    END MAIN